# -*- coding: utf-8 -*-
import sys

sys.path.insert(0, '../archivos')
sys.path.insert(0, 'archivos')

import archivos_pn
import unittest2
import teamcity
import teamcity.unittestpy
import cons
import db
import cx_Oracle

stack_msg = []
registros = []

class pruebas_archivos_pn(unittest2.TestCase):

	def test_validar_encabezado(self):
		global stack_msg
		self.assertEqual(archivos_pn.validar_encabezado("EPN01", stack_msg), True)

	def test_validar_encabezado_tipo_registro(self):
		self.assertEqual(archivos_pn.validar_encabezado("SPN02", []), False)
		self.assertEqual(archivos_pn.validar_encabezado(" PN02", []), False)

	def test_validar_encabezado_proceso(self):
		self.assertEqual(archivos_pn.validar_encabezado("E  02", []), False)
		self.assertEqual(archivos_pn.validar_encabezado("ENV02", []), False)
		self.assertEqual(archivos_pn.validar_encabezado("EAM02", []), False)

	def test_validar_encabezado_id_ars_en_blanco(self):
		self.assertEqual(archivos_pn.validar_encabezado("EPN  ", []), False)

	def test_validar_encabezado_id_ars_con_caracteres(self):

		i = 0
		for c in cons.char_especiales_array: 
		    self.assertEqual(archivos_pn.validar_encabezado("EPN0" + cons.char_especiales_array[i], []), False)
		    i = i + 1

	def test_validar_encabezado_longitud_menor(self):
		self.assertEqual(archivos_pn.validar_encabezado("EPN1", []), False)

	def test_validar_encabezado_longitud_mayor(self):
		self.assertEqual(archivos_pn.validar_encabezado("EPN112145", []), False)

	def test_validar_detalle(self):
		global stack_msg
		self.assertEqual(archivos_pn.validar_detalle("DB12345678901234567890                                                                                                                                                                                 MS80961618238095672127                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 E    P64", stack_msg), True)
		self.assertEqual(archivos_pn.validar_detalle("DA12345678901234567890                                                                                                                                                                                 MS80961618238095672127                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 T       ", stack_msg), True)
		
	def test_validar_detalle_tipo_registro(self):
		self.assertEqual(archivos_pn.validar_detalle(" A00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("SA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_tipo_novedad(self):
		self.assertEqual(archivos_pn.validar_detalle("DC00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("D 00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_nro_formulario(self):
		self.assertEqual(archivos_pn.validar_detalle("DA     123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DAabcjd123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_nro_pensionado(self):
		self.assertEqual(archivos_pn.validar_detalle("DA000001234512345asdfg          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA0000012345     12345          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	'''def test_validar_detalle_fecha_nacimiento(self):
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                        001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                00000000001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                29111987001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)'''

	def test_validar_detalle_nacionalidad(self):
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129  1MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129   MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129asdMS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_sexo(self):
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001 S                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001AS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_estado_civil(self):
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001M                                                                                 calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MP                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_direccion(self):
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                                                                                                                                                                                                                                    000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		
	def test_validar_detalle_municipio(self):
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                                 S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           adbchtS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_hijos_menor_edad(self):
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                P62", []), False)
		self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001D                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               P62", []), False)

	def test_validar_detalle_motivo_baja(self):
		#self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ", []), False)
		#self.assertEqual(archivos_pn.validar_detalle("DA00000123451234567891          kerlin santiago                                   de la cruz                                                                                                19871129001MS                                                                                calle paz y bien numero 5                                                                                                                                                                                           000001S                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               001", []), False)
		pass

	def test_validar_detalle_nss_conyugue(self):
		pass

	def test_validar_sumario(self):
		global stack_msg
		self.assertEqual(archivos_pn.validar_sumario("S000000", stack_msg), True)

	def test_validar_sumario_tipo_registro(self):
		self.assertEqual(archivos_pn.validar_sumario("C000000", []), False)
		self.assertEqual(archivos_pn.validar_sumario(" 000000", []), False)

	def test_validar_sumario_con_espacios(self):
		self.assertEqual(archivos_pn.validar_sumario("S      ", []), False)
		self.assertEqual(archivos_pn.validar_sumario("S   000", []), False)

	def test_validar_sumario_con_letras(self):
		self.assertEqual(archivos_pn.validar_sumario("S00asd0", []), False)
		self.assertEqual(archivos_pn.validar_sumario("S!@#$%^", []), False)

	def test_validar_sumario_longitud_menor(self):
		self.assertEqual(archivos_pn.validar_sumario("S000", []), False)

	def test_validar_sumario_longitud_mayor(self):
		self.assertEqual(archivos_pn.validar_sumario("S0000000000", []), False)

	def test_validar_sumario_en_blanco(self):
		self.assertEqual(archivos_pn.validar_sumario("       ", []), False)

	'''def test_insertar_detalle_many(self):

		oConn = cx_Oracle.connect(db.connString())
		oCurs = oConn.cursor()
		
		global stack_msg		
		registros = ['DA000001084300000658940051103251MARIA ALTAGRACIA                                  SIERRA                                  VASQUEZ                                 C08100004772              1        01FS000000000000000000000000000000                                                  C/ CAPOTILLO # 28                                                                                                                                                                                                   000081N00000000000000000000000000000000000000000000000000                                                                                                                                                           00000000000000000000000000000000000000000                                                                                                                                                                                                                                                          000000                                                                                                                                                                                                                                                                                                                                                              000000     p23']
		id_envio = ''
		
		self.assertRaises(TypeError, lambda: archivos_pn.insertar_detalle_many(registros, id_envio, oCurs, stack_msg), [])
		
		oConn.commit()
		oCurs.close()
		oConn.close()'''

	def tearDown(self):
		global stack_msg

		if len(stack_msg) > 0:
			print "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
			for x in stack_msg:
			    print x
			print "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

if __name__ == '__main__':

    #unittest2.main()

    #if teamcity.underTeamcity():
    #    runner = teamcity.unittestpy.TeamcityTestRunner()
    #    unittest2.main(testRunner=runner)
    #else:
    #    suite = unittest2.TestLoader().loadTestsFromTestCase(Funciones)
    #    unittest2.TextTestRunner(verbosity=2).run(suite)
    pass 
