'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.21006.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class StringsEncabezado
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BCRDFileServices.StringsEncabezado", GetType(StringsEncabezado).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El concepto del pago no puede estar en blanco o nulo..
        '''</summary>
        Friend Shared ReadOnly Property codigoBICentidadCR() As String
            Get
                Return ResourceManager.GetString("codigoBICentidadCR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El codigo BI Cantidad DR debe contener 11 caracteres..
        '''</summary>
        Friend Shared ReadOnly Property codigoBICentidadCRLenght() As String
            Get
                Return ResourceManager.GetString("codigoBICentidadCRLenght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El codigo BI Cantidad DB no puede estar en blanco o nulo..
        '''</summary>
        Friend Shared ReadOnly Property codigoBICentidadDB() As String
            Get
                Return ResourceManager.GetString("codigoBICentidadDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El codigo BI Cantidad DB debe contener 11 caracteres..
        '''</summary>
        Friend Shared ReadOnly Property codigoBICentidadDBLenght() As String
            Get
                Return ResourceManager.GetString("codigoBICentidadDBLenght", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El codigo del pais relacionado con BI Cantidad DB no es correcto.
        '''</summary>
        Friend Shared ReadOnly Property codigoBICentidadDBPais() As String
            Get
                Return ResourceManager.GetString("codigoBICentidadDBPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El concepto del pago no puede estar en blanco o nulo..
        '''</summary>
        Friend Shared ReadOnly Property conceptopago() As String
            Get
                Return ResourceManager.GetString("conceptopago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El estado del archivo del portal no puede estan en blanco o nulo..
        '''</summary>
        Friend Shared ReadOnly Property estadoarchivoenportal() As String
            Get
                Return ResourceManager.GetString("estadoarchivoenportal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La fecha generacion del archivo no puede ser nula..
        '''</summary>
        Friend Shared ReadOnly Property fechageneracion() As String
            Get
                Return ResourceManager.GetString("fechageneracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La fecha no puede ser nula..
        '''</summary>
        Friend Shared ReadOnly Property FechaValorCRLBTR() As String
            Get
                Return ResourceManager.GetString("FechaValorCRLBTR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La moneda no puede estar en blanco o nula..
        '''</summary>
        Friend Shared ReadOnly Property moneda() As String
            Get
                Return ResourceManager.GetString("moneda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El codigo de moneda debe ser de 3 caracteres.
        '''</summary>
        Friend Shared ReadOnly Property monedalength() As String
            Get
                Return ResourceManager.GetString("monedalength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El numero de de lote no puede ser 0..
        '''</summary>
        Friend Shared ReadOnly Property numerolote() As String
            Get
                Return ResourceManager.GetString("numerolote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El Numero de lote no puede ser nulo..
        '''</summary>
        Friend Shared ReadOnly Property numeroloteNull() As String
            Get
                Return ResourceManager.GetString("numeroloteNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El tipo no puede estar en blanco o  nulo..
        '''</summary>
        Friend Shared ReadOnly Property tipo() As String
            Get
                Return ResourceManager.GetString("tipo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El monto de control debe ser mayor que cero.
        '''</summary>
        Friend Shared ReadOnly Property totalMontosControl() As String
            Get
                Return ResourceManager.GetString("totalMontosControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El monto de no puede estar en blanco o nulo..
        '''</summary>
        Friend Shared ReadOnly Property totalMontosControNull() As String
            Get
                Return ResourceManager.GetString("totalMontosControNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El total de registros no puede ser cero.
        '''</summary>
        Friend Shared ReadOnly Property totalRegistrosControl() As String
            Get
                Return ResourceManager.GetString("totalRegistrosControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El total de registros no puede estar en blanco o nulo..
        '''</summary>
        Friend Shared ReadOnly Property totalRegistrosControlNull() As String
            Get
                Return ResourceManager.GetString("totalRegistrosControlNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El TRN no puede estar en blanco o nulo..
        '''</summary>
        Friend Shared ReadOnly Property TrnopcrLBTR() As String
            Get
                Return ResourceManager.GetString("TrnopcrLBTR", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
