BEGIN
   EXECUTE IMMEDIATE 
   'CREATE MATERIALIZED VIEW SUIRPLUS.ARS_DEP_ADICIONALES_MV
    REFRESH FORCE ON DEMAND
    AS
    SELECT
      NSS_TITULAR AS ID_NSS_TITULAR,
      NSS_DEPENDIENTE_ADICIONAL AS ID_NSS_DEPENDIENTE,
      NSS_CONYUGE AS ID_NSS_CONYUGE,
      CODIGO_PARENTESCO AS ID_PARENTESCO
     FROM TSS_DEPENDIENTES_ADIC_MV@UNIPRO_DBL';
 
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.ARS_DEP_ADICIONALES_MV.ID_NSS_TITULAR IS ''Numero de Seguridad Social del titular del nucleo.''';
 
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.ARS_DEP_ADICIONALES_MV.ID_NSS_DEPENDIENTE IS ''Numero de Seguridad Social del dependiente adicional.''';
 
   EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.ARS_DEP_ADICIONALES_MV.ID_NSS_CONYUGE IS ''Numero de Seguridad Social del conyuge del nucleo.''';

   EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.ARS_DEP_ADICIONALES_MV.ID_PARENTESCO IS ''Codigo del parentesco del dependiente adicional asociado al titular.''';
 END;