DECLARE
  v_count pls_integer;
BEGIN  
--1)Eliminar Vistas Materializadas para crear vistas naturales
 SELECT COUNT(*)
   INTO v_count
 FROM ALL_MVIEWS 
 WHERE MVIEW_NAME = 'SFC_DET_AJUSTES_MV'
 AND OWNER = 'UNIPAGO';

IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW UNIPAGO.SFC_DET_AJUSTES_MV';
END IF;

 SELECT COUNT(*)
   INTO v_count
 FROM ALL_MVIEWS 
 WHERE MVIEW_NAME = 'SFC_DET_FACTURAS_MV'
 AND OWNER = 'UNIPAGO';

IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW UNIPAGO.SFC_DET_FACTURAS_MV';
END IF;

 SELECT COUNT(*)
   INTO v_count
 FROM ALL_MVIEWS 
 WHERE MVIEW_NAME = 'SFC_DET_DEPENDIENTE_FACTURA_MV'
 AND OWNER = 'UNIPAGO';

IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW UNIPAGO.SFC_DET_DEPENDIENTE_FACTURA_MV';
END IF;

END;
/*---------------------------------------------------------*/