CREATE MATERIALIZED VIEW SUIRPLUS.SUIR_R_SOL_ASIG_NSS_MENORES_MV
AS 
-- Formatted on 2016/09/29 5:13:37 PM (QP5 v5.215.12089.38647)
SELECT N_NUM_CONTROL,
       N_ID_REGISTRO,
       ACTA_MUNICIPIO AS C_ACTA_MUNICIPIO,
       C_ACTA_OFICIALIA,
       C_ACTA_LIBRO,
       C_ACTA_FOLIO,
       C_ACTA_ACTA,
       C_ACTA_ANIO,
       C_APEPAT,
       C_APEMAT,
       PRIMER_NOM,
       C_NOMBRE2,
       C_FECHA_NACIMIENTO,
       C_SEXO,
       FECHA_SOLICITUD,
       CODIGO_PENDIENTE,
       C_CVE_ENTIDAD,
       NSS_TITULAR,
       C_DEP_EXTRANJERO AS C_DEP_MENOR_EXTRANJERO,
	   C_DEP_EXTRANJERO,
       C_ID_NACIONALIDAD,
	   N_TIPO_DOCUMENTO,
	   C_NUMERO_DOCUMENTO,
	   N_CVE_PARENTESCO
  FROM SUIR_R_SOL_ASIG_NSS_MENORES_MV@UNIPRO_DBL A
 WHERE  NOT EXISTS --REGISTROS QUE NO HALLAN SIDO CREADOS PREVIAMENTE EN EL DETALLE
 (
  SELECT 1
  FROM SUIRPLUS.NSS_DET_SOLICITUDES_T D
  WHERE D.NUM_CONTROL = A.N_NUM_CONTROL
    AND D.ID_CONTROL = A.N_ID_REGISTRO
 )
;