BEGIN
  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_ARS_ACTUALIZACION_ACTA
  BEFORE INSERT OR UPDATE ON SUIRPLUS.ARS_ACTUALIZACION_ACTAS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_ARS_ACTUALIZACION_VIST
  BEFORE INSERT OR UPDATE ON SUIRPLUS.ARS_ACTUALIZACION_VISTAS_T for each row
  Begin
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_ARS_DET_ACTUALIZACION_
  BEFORE INSERT OR UPDATE ON SUIRPLUS.ARS_DET_ACTUALIZACION_ACTAS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_ARS_DET_SOLICITUD_NSS_
  BEFORE INSERT OR UPDATE ON SUIRPLUS.ARS_DET_SOLICITUD_NSS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_ARS_DET_SOLICITUD_T_TR
  BEFORE INSERT OR UPDATE ON SUIRPLUS.ARS_DET_SOLICITUD_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_ARS_SOLICITUD_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.ARS_SOLICITUD_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_CER_CERTIFICACIONES_T_
  BEFORE INSERT OR UPDATE ON SUIRPLUS.CER_CERTIFICACIONES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_CER_ROLES_CERTIFICACIO
  BEFORE INSERT OR UPDATE ON SUIRPLUS.CER_ROLES_CERTIFICACIONES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_CER_SOL_CERTIFICACIONE
  BEFORE INSERT OR UPDATE ON SUIRPLUS.CER_SOL_CERTIFICACIONES_T for each row
  Begin
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_JCE_ACTUALIZACION_T_TR
  BEFORE INSERT OR UPDATE ON SUIRPLUS.JCE_ACTUALIZACION_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_LGL_ACUERDOS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.LGL_ACUERDOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_LGL_SOLICITUDES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.LGL_SOLICITUDES_T for each row
  Begin
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_NCH_CUENTAS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.NCH_CUENTAS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_NCH_PROCESOS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.NCH_PROCESOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_NCH_SUBPROCESOS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.NCH_SUBPROCESOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_NSS_DET_SOLICITUDES_T_
  BEFORE INSERT OR UPDATE ON SUIRPLUS.NSS_DET_SOLICITUDES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_NSS_DET_SOLICITUD_EN_P
  BEFORE INSERT OR UPDATE ON SUIRPLUS.NSS_DET_SOLICITUD_EN_PROCESO_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_NSS_EVALUACION_VISUAL_
  BEFORE INSERT OR UPDATE ON SUIRPLUS.NSS_EVALUACION_VISUAL_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_NSS_SOLICITUDES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.NSS_SOLICITUDES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_OFC_DOCUMENTACION_T_TR
  BEFORE INSERT OR UPDATE ON SUIRPLUS.OFC_DOCUMENTACION_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SEG_AUD_USUARIO_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SEG_AUD_USUARIO_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SEG_ERROR_ACTAS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SEG_ERROR_ACTAS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SEH_DET_NOV_TMP_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SEH_DET_NOV_TMP_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SEH_MOTIVO_BAJA_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SEH_MOTIVO_BAJA_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SEL_EMPLEADORES_TMP_T_
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SEL_EMPLEADORES_TMP_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SEL_STATUS_HISTORICO_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SEL_STATUS_HISTORICO_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_APLICACIONES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_APLICACIONES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_DET_NACHA_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_DET_NACHA_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_DET_RECAUDO_IBANKI
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_DET_RECAUDO_IBANKING_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_EQUIVALENCIAS_IR13
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_EQUIVALENCIAS_IR13_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_IR17_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_IR17_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_NACHA_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_NACHA_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_RANGOS_ANUALES_ISR
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_RANGOS_ANUALES_ISR_NEW_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_RANGOS_ANUALES_IS
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_RANGOS_ANUALES_ISR_PEN_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_RECAUDO_IBANKING_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_RECAUDO_IBANKING_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_RENGLONES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_RENGLONES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_RENGLON_NOMINA_T_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_RENGLON_NOMINA_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_RESUMEN_IR13_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_RESUMEN_IR13_T for each row
  Begin
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_TIPO_AJUSTES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_TIPO_AJUSTES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SFC_TIPO_NOMINAS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SFC_TIPO_NOMINAS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_ADICIONALES_RES_26
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_ADICIONALES_RES_265_01_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_ADICIONALES_RES_2
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_ADICIONALES_RES_265_02_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_AUD_REPRESENTANTES
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_AUD_REPRESENTANTES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_CIUDADANOS_API_T_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_CIUDADANOS_API_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_CIUDADANOS_CANCELA
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_CIUDADANOS_CANCELADOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_CIUDADANOS_ULT_T_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_CIUDADANOS_ULT_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_CIU_CAMBIOS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_CIU_CAMBIOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_CLASE_EMPRESA_T_TR
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_CLASE_EMPRESA_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_CLASE_EMP_DOCS_T_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_CLASE_EMP_DOCS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_DET_CIUDADANOS_API
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_DET_CIUDADANOS_API_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_ESCALA_SALARIAL_T_
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_ESCALA_SALARIAL_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_ESTADISTICAS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_ESTADISTICAS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_HISTORICO_DOCUMENT
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_HISTORICO_DOCUMENTOS_T for each row
  Begin
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_HIS_DOCUMENTOS_T_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_HIS_DOCUMENTOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_INFORMES_AUDITORIA
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_INFORMES_AUDITORIA_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_INHABILIDAD_EMPLEA
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_INHABILIDAD_EMPLEADORES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_INHABILIDAD_PROCES
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_INHABILIDAD_PROCESOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_LOCALIDADES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_LOCALIDADES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_MENORES_CANCELADOS
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_MENORES_CANCELADOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_MOTIVOS_PASAPORTES
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_MOTIVOS_PASAPORTES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_OCUPACIONES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_OCUPACIONES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_PASAPORTES_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_PASAPORTES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_SECTORES_SALARIALE
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_SECTORES_SALARIALES_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_TIPO_ARCHIVOS_T_TR
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_TIPO_ARCHIVOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_TIPO_INGRESO_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_TIPO_INGRESO_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_TMP_MOVIMIENTO_REC
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_TMP_MOVIMIENTO_RECAUDO_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SRE_TURNOS_T_TRG
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SRE_TURNOS_T for each row
  Begin 
    IF :old.ULT_USUARIO_ACT is not null AND :new.ULT_USUARIO_ACT is null THEN
      :new.ULT_USUARIO_ACT := :old.ULT_USUARIO_ACT;
    END IF;
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SUB_ERRORES_SISALRIL_O
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SUB_ERRORES_SISALRIL_OK_T for each row
  Begin
    :new.ULT_FECHA_ACT := sysdate;
  End;';

  EXECUTE IMMEDIATE '
  CREATE OR REPLACE TRIGGER SUIRPLUS.DATE_ON_SUIR_SOL_ASIG_CEDULA_T
  BEFORE INSERT OR UPDATE ON SUIRPLUS.SUIR_SOL_ASIG_CEDULA_T for each row
  Begin
    :new.ULT_FECHA_ACT := sysdate;
  End;';
END;