DECLARE
  v_count pls_integer;
BEGIN
  SELECT COUNT(*)
   INTO v_count
   FROM ALL_MVIEWS 
  WHERE MVIEW_NAME = 'SUIR_R_SOL_ASIG_NSS_MENORES_MV'
    AND OWNER = 'SUIRPLUS';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW SUIRPLUS.SUIR_R_SOL_ASIG_NSS_MENORES_MV';
  END IF;
END;