CREATE OR REPLACE PROCEDURE NSS_GET_CIUDADANO
(
 P_TIPO IN SUIRPLUS.SRE_CIUDADANOS_T.TIPO_DOCUMENTO%TYPE,
 P_NO_DOCUMENTO IN SUIRPLUS.SRE_CIUDADANOS_T.NO_DOCUMENTO%TYPE,
 P_CURSOR OUT SYS_REFCURSOR,
 P_RESULTADO OUT VARCHAR2
) AS
BEGIN
  OPEN P_CURSOR FOR
    SELECT C.*, N.NACIONALIDAD_DES, I.CANCELACION_DES
      FROM SUIRPLUS.SRE_CIUDADANOS_T C
      LEFT JOIN SUIRPLUS.SRE_NACIONALIDAD_T N
        ON N.ID_NACIONALIDAD = C.ID_NACIONALIDAD
      LEFT JOIN SUIRPLUS.SRE_INHABILIDAD_JCE_T I
        ON I.ID_CAUSA_INHABILIDAD = C.ID_CAUSA_INHABILIDAD
       AND I.TIPO_CAUSA = C.TIPO_CAUSA    
     WHERE C.TIPO_DOCUMENTO = P_TIPO
       AND C.NO_DOCUMENTO = P_NO_DOCUMENTO;

  P_RESULTADO := 'OK';
EXCEPTION WHEN OTHERS THEN
  P_RESULTADO := SQLERRM;
END;