BEGIN
  EXECUTE IMMEDIATE 
  'CREATE MATERIALIZED VIEW SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV
   REFRESH FORCE ON DEMAND
   AS
   SELECT
     ARS AS ID_ARS,
     NSS_TITULAR AS ID_NSS_TITULAR,
     NSS_DEPENDIENTE AS ID_NSS_DEPENDIENTE,
     PARENTESCO AS ID_PARENTESCO,
     TIPO_AFILIADO AS TIPO_AFILIADO,
     PERIODO_FACTURA,
     N_TIPO_FACTURABLE AS TIPO_FACTURABLE,
     ESTUDIANTE,
     DISCAPACITADO,
     N_CVE_INSTITUCION AS ID_INSTITUCION
    FROM TSS_CARTERA_PENSIONADOS_MV@UNIPRO_DBL';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.ID_ARS IS ''Código de la ARS correspondiente al Plan Especial de Salud Pensionados.''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.ID_NSS_TITULAR IS ''Número de Seguridad Social del titular.''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.ID_NSS_DEPENDIENTE IS ''Número de Seguridad Social del dependiente.''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.ID_PARENTESCO IS ''Código del parentesco asociado al afiliado. Solo aplica para dependientes.''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.TIPO_AFILIADO IS ''Código del tipo de afiliado. Posibles valores (T=Titular, D=Directo, A=Adicional).''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.PERIODO_FACTURA IS ''Periodo de facturación en formato AAAAMM.''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.TIPO_FACTURABLE IS ''Indica el tipo de facturable. Posibles valores 1=FACTURABLE.''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.ESTUDIANTE IS ''Indica si el dependiente está marcado como Estudiante. Posibles Valores (S=Si es estudiante, N=No es estudiante).''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.DISCAPACITADO IS ''Indica si el dependiente está marcado como Discapacitado. Posibles Valores (S=Es Discapacitado, N=No es Discapacitado).''';

  EXECUTE IMMEDIATE 'COMMENT ON COLUMN SUIRPLUS.RPN_CARTERA_PENSIONADOS_MV.ID_INSTITUCION IS ''Clave de la institución a la que corresponde el Pensionado. Posibles Valores (1=Pensionados de la Policía Nacional, 2=Pensionados del Sector Salud, 3=Pensionados de las Fuerzas Armadas).''';
END;