BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE FORCE VIEW  UNIPAGO.SFC_DET_DEPENDIENTE_FACTURA_MV
AS
SELECT a.ID_REFERENCIA n_no_referencia,
       a.ID_NSS_TITULAR,
       a.SECUENCIA,
       a.ID_NSS_DEPENDIENTE_ADIC,
       a.PER_CAPITA_FONAMAT
  FROM SUIRPLUS.SFC_DET_DEPENDIENTES_FACTURA_T  a,
       SUIRPLUS.sfc_facturas_T                  F,
       SUIRPLUS.SEG_USUARIO_id_v                   U
 WHERE     a.id_referencia = F.ID_referencia
       AND F.STATUS NOT IN (''CA'', ''RE'', ''PA'')
       AND F.ID_USUARIO_AUTORIZA IS NOT NULL
       AND F.NO_AUTORIZACION IS NOT NULL
       AND F.ID_USUARIO_AUTORIZA = U.ID_USUARIO';
       
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN "UNIPAGO"."SFC_DET_DEPENDIENTE_FACTURA_MV"."N_NO_REFERENCIA" IS ''Numero de refrencia de la factura''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN "UNIPAGO"."SFC_DET_DEPENDIENTE_FACTURA_MV"."ID_NSS_TITULAR" IS ''Numero de seguridad social del titular, ver SUIRPLUS.SRE_CIUDADANOS_T''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN "UNIPAGO"."SFC_DET_DEPENDIENTE_FACTURA_MV"."SECUENCIA" IS ''Numero de secuencia del registro''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN "UNIPAGO"."SFC_DET_DEPENDIENTE_FACTURA_MV"."ID_NSS_DEPENDIENTE_ADIC" IS ''Numero de seguridad social del dependiente adicional, ver SUIRPLUS.SRE_CIUDADANOS_T''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN "UNIPAGO"."SFC_DET_DEPENDIENTE_FACTURA_MV"."PER_CAPITA_FONAMAT" IS ''Monto del percapita de FONAMAT''';
  END;