//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepcionDocuments.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecepcionDoc
    {
        public int id { get; set; }
        public string No_memo { get; set; }
        public string Name { get; set; }
        public string RealNameMemo { get; set; }
        public byte[] DocPath { get; set; }
        public string Recibido_por { get; set; }
        public string Entregado_por { get; set; }
        public Nullable<System.DateTime> Fecha_registro { get; set; }
    }
}
