//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Dietas
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion_max
    {
        public int ID { get; set; }
        public Nullable<int> EMP_COD { get; set; }
        public Nullable<float> ASIGACION_MAX { get; set; }
        public Nullable<float> DESAYUNO { get; set; }
        public Nullable<float> ALMUERZO { get; set; }
        public Nullable<float> CENA { get; set; }
        public Nullable<float> ALOJAMIENTO { get; set; }
    }
}
