//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Dietas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.empleados = new HashSet<empleados>();
        }
    
        public int ID { get; set; }
        public string Categoria1 { get; set; }
        public Nullable<double> AsignacionMax { get; set; }
        public Nullable<double> Desayuno { get; set; }
        public Nullable<double> Almuerzo { get; set; }
        public Nullable<double> Cena { get; set; }
        public Nullable<double> Alojamiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleados> empleados { get; set; }
    }
}
