//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Dietas
{
    using System;
    using System.Collections.Generic;
    
    public partial class dietas
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> HoraFecha_Partida { get; set; }
        public Nullable<System.DateTime> HoraFecha_Retorno { get; set; }
        public Nullable<bool> Desayuno { get; set; }
        public Nullable<bool> Almuerzo { get; set; }
        public Nullable<bool> Cena { get; set; }
        public Nullable<bool> Alojamiento { get; set; }
        public string Provincia { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public string CartaRuta { get; set; }
        public string Memo { get; set; }
        public string Actividad { get; set; }
    }
}
