//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Dietas
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int ID { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string CARGO { get; set; }
        public string TEL { get; set; }
        public Nullable<int> CATEGORIAID { get; set; }
        public string CEDULA { get; set; }
        public string DIRECCION { get; set; }
        public string OTRA_DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string CELULAR_OTRO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<float> SUELDO_MENSUAL { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
