//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Dietas
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetDietasNoPagadas2
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string CartaRuta { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> DCA { get; set; }
        public Nullable<bool> Transporte { get; set; }
        public Nullable<bool> RRHH { get; set; }
        public Nullable<bool> Auditoria { get; set; }
        public Nullable<bool> Financiero { get; set; }
        public Nullable<bool> Nomina { get; set; }
        public Nullable<bool> Pagada { get; set; }
        public string Provincia { get; set; }
        public string Codigo { get; set; }
    }
}
