//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Dietas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DireccionCalidadEntities : DbContext
    {
        public DireccionCalidadEntities()
            : base("name=DireccionCalidadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<status_dietas> status_dietas { get; set; }
        public virtual DbSet<dietas> dietas { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<asignacion_max> asignacion_max { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<GetDietasNoPagadas2> GetDietasNoPagadas2 { get; set; }
    
        public virtual ObjectResult<get_dieta_Result2> get_dieta(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_dieta_Result2>("get_dieta", idParameter);
        }
    }
}
