//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Dietas
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_dietas
    {
        public int ID { get; set; }
        public Nullable<int> ID_dieta { get; set; }
        public Nullable<bool> DCA { get; set; }
        public Nullable<System.DateTime> Fecha_Salida_DCA { get; set; }
        public Nullable<bool> Transporte { get; set; }
        public Nullable<System.DateTime> Fecha_Salida_Transporte { get; set; }
        public Nullable<bool> RRHH { get; set; }
        public Nullable<System.DateTime> Fecha_Salida_RRHH { get; set; }
        public Nullable<bool> Auditoria { get; set; }
        public Nullable<System.DateTime> Fecha_Salida_Auditoria { get; set; }
        public Nullable<bool> Financiero { get; set; }
        public Nullable<System.DateTime> Fecha_Salida_Financiero { get; set; }
        public Nullable<bool> Nomina { get; set; }
        public Nullable<System.DateTime> Fecha_Salida_Nomina { get; set; }
        public Nullable<bool> Pagada { get; set; }
    }
}
